# Generated by Django 5.2.1 on 2026-07-09 03:21

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0207_remove_redundant_indexes'),
        ('extras', '0128_tableconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('config_format', models.CharField(default='raw', max_length=30)),
                ('config', models.TextField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plugin_configs', to='dcim.device')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name_plural': 'Configs',
                'ordering': ('device', 'config_format'),
                'constraints': [models.UniqueConstraint(fields=('device', 'config_format'), name='netbox_config_config_unique_device_format')],
            },
        ),
    ]
